name: Run Python Script to Generate HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      - name: Clear pip cache
        run: |
          pip cache purge
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python plots.py

      - name: Upload HTML file to Release
        uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: 3d_energy_probability_distribution.html
          asset_name: 3d_energy_probability_distribution.html
          asset_content_type: text/html
            
